server:
  port: 8080

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  tracing:
    sampling:
      probability: 1.0