server:
  port: 8080

opentelemetry:
  traces:
    exporter:
      jaeger:
        endpoint: ${JAEGER_ENDPOINT:http://localhost:14250}
        service-name: ${JAEGER_SERVICE_NAME:myservice}


management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: